// www/app/playground/page.tsx
"use client";

import { CodeEditor } from "@/components/code-editor";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";
import { run } from "@/lib/runCode";
import { Share, Copy } from "lucide-react";
import { useRef, useState } from "react";
import { toast } from "sonner";

type State = "default" | "loadingGame" | "playingGame";

export default function Playground() {
  const [code, setCode] = useState("");
  const gameCanvas = useRef<HTMLCanvasElement | null>(null);
  const wasm = useRef<{ __exit: () => void } | null>(null);
  const [state, setState] = useState<State>("default");

  async function copyCodeToClipboard() {
    await navigator.clipboard.writeText(code);
    toast("Code copied to clipboard");
  }

  return (
    <main className="p-4 h-screen">
      <ResizablePanelGroup
        direction="horizontal"
        onLayout={() => {
          const canvas = gameCanvas.current;
          if (canvas) {
            const parent = canvas.parentElement!;
            canvas.style.width = `${parent.clientWidth}px`;
            canvas.style.height = `${parent.clientWidth * (9 / 16)}px`;
          }
        }}
      >
        <ResizablePanel
          defaultSize={60}
          minSize={20}
          className="flex flex-col gap-4"
        >
          <Card className="p-4 flex flex-row justify-between">
            <Button
              className="transition"
              onClick={async () => {
                setState("loadingGame");
                const result = await run(code, "gameCard");
                setState("playingGame");
                gameCanvas.current = result.gameCanvas;
                wasm.current = result.wasm;
              }}
              disabled={state === "loadingGame"}
            >
              Run
            </Button>
            <div className="flex flex-row gap-4">
              <Button
                variant="outline"
                size="icon"
                onClick={copyCodeToClipboard}
              >
                <Copy className="h-4 w-4" />
              </Button>
              <Button variant="outline" size="icon">
                <Share className="h-4 w-4" />
              </Button>
            </div>
          </Card>
          <Card className="p-4 h-full">
            <CodeEditor onChange={(code) => setCode(code)}></CodeEditor>
          </Card>
        </ResizablePanel>
        <ResizableHandle withHandle className="mx-4" />
        <ResizablePanel
          defaultSize={40}
          minSize={20}
          className="flex flex-col gap-4"
        >
          <Card className="aspect-video">
            <div id="gameCard" className="w-full h-full"></div>
          </Card>
          <Card className="flex-grow p-4 text-sm"></Card>
        </ResizablePanel>
      </ResizablePanelGroup>
    </main>
  );
}

// www/src/routes/playground/+page.svelte
<script lang="ts">
    import Editor from '$lib/components/Editor.svelte';
    import { Button } from '$lib/components/ui/button';
    import { Card } from '$lib/components/ui/card';
    import * as Resizable from '$lib/components/ui/resizable';
    import Actions from './Actions.svelte';
    import { play as load } from '$lib/play';

    const gameCanvasParentId = 'game-container';
    let gameCanvasParent: HTMLDivElement;

    let editor: Editor;
    let code: string;

    let gameCanvas: HTMLCanvasElement | null = null;
    let wasm: any | null = null;

    async function play() {
        if (wasm) wasm.__exit();
        if (gameCanvas) gameCanvas.remove();
        let result = await load({
            code,
            version: '0.13',
            channel: 'nightly',
            parentId: gameCanvasParentId,
        });
        gameCanvas = result.gameCanvas;
        wasm = result.wasm;
    }

    function resizeGameCanvas() {
        if (!gameCanvas) return;
        gameCanvas.style.width = `${gameCanvasParent.clientWidth}px`;
        gameCanvas.style.height = `${gameCanvasParent.clientWidth * (9 / 16)}px`;
    }
</script>

<div class="h-screen p-4">
    <Resizable.PaneGroup direction="horizontal">
        <Resizable.Pane
            defaultSize={60}
            minSize={20}
            onResize={() => {
                editor.layout();
                resizeGameCanvas();
            }}
            class="flex flex-col gap-4"
        >
            <Card class="flex flex-row justify-between p-4">
                <Button class="font-semibold" on:click={play}>Play</Button>
                <Actions />
            </Card>
            <Card class="h-full p-4">
                <Editor bind:this={editor} bind:code />
            </Card>
        </Resizable.Pane>
        <Resizable.Handle withHandle class="mx-4" />
        <Resizable.Pane defaultSize={40} minSize={20} class="flex flex-col gap-4">
            <Card class="aspect-video">
                <div
                    bind:this={gameCanvasParent}
                    id={gameCanvasParentId}
                    class="h-full w-full"
                ></div>
            </Card>
            <Card class="flex-grow overflow-auto p-4 text-sm"></Card>
        </Resizable.Pane>
    </Resizable.PaneGroup>
</div>
