// www/components/console.tsx
import { useEffect, useRef } from "react";

export function Console(props: { items: ConsoleItem[] }) {
  const consoleBottomRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (consoleBottomRef.current) {
      consoleBottomRef.current.scrollIntoView();
    }
  }, [props.items]);

  const content = props.items.map((item, n) => {
    if (item.kind === "Stdout") {
      return <p key={n}>{item.text}</p>;
    } else if (item.kind === "Log") {
      let color = null;
      switch (item.level) {
        case "TRACE":
          color = "text-cyan-500";
          break;
        case "DEBUG":
          color = "text-yellow-500";
          break;
        case "INFO":
          color = "text-green-500";
          break;
        case "WARN":
          color = "text-orange-500";
          break;
        case "ERROR":
          color = "text-red-500";
          break;
      }
      return (
        <div key={n}>
          <span className={color}>{item.level}</span>{" "}
          <span className="text-neutral-500">{item.location}</span>{" "}
          {item.message}
        </div>
      );
    }
  });

  return (
    <>
      <pre className="text-wrap">
        {content}
        <div ref={consoleBottomRef}></div>
      </pre>
    </>
  );
}

export type ConsoleItem = Stdout | ConsoleLog;

export type Stdout = {
  kind: "Stdout";
  text: string;
};

export type LogLevel = "TRACE" | "DEBUG" | "INFO" | "WARN" | "ERROR";
export type ConsoleLog = {
  kind: "Log";
  level: LogLevel;
  location: string;
  message: string;
};

// www/src/routes/playground/Console.svelte
<script context="module" lang="ts">
    export type ConsoleItem = Stdout | ConsoleLog;
    type Stdout = {
        kind: 'Stdout';
        text: string;
    };
    type LogLevel = 'TRACE' | 'DEBUG' | 'INFO' | 'WARN' | 'ERROR';
    type ConsoleLog = {
        kind: 'Log';
        level: LogLevel;
        location: string;
        message: string;
    };
</script>

<script lang="ts">
    export let consoleItems: ConsoleItem[];

    const logColors = {
        TRACE: 'text-cyan-500',
        DEBUG: 'text-yellow-500',
        INFO: 'text-green-500',
        WARN: 'text-orange-500',
        ERROR: 'text-red-500',
    };
</script>

{#each consoleItems as item, n (n)}
    {#if item.kind === 'Stdout'}
        <p>{item.text}</p>
    {:else if item.kind === 'Log'}
        <div>
            <span class={logColors[item.level]}>{item.level}</span>{' '}
            <span class="text-neutral-500">{item.location}</span>{' '}
            {item.message}
        </div>
    {/if}
{/each}
